---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cun8c.
--- DateTime: 2019/7/1 11:35
---将数据写入到redis
---引入redis模块
local redis = require("resty.redis")

---创建redis的实例
local red = redis:new()

---创建redis的连接
local  ok, err = red:connect("192.168.83.110", 6379)
---ok是boolean值，如果连接成功，ok：true， 连接失败，ok：false
if not ok then
    --连接失败
    ngx.say("connection redis is failed:", err)
    return
end

---向redis写数据
local ok, err = red:set("openResTy-lua", "redis")
if not ok then
    ngx.say("send message is failed:", err)
    return
end

--打印写入redis成功的消息
ngx.say("send message ok", ok)

-- 连接池大小是100个，并且设置最大的空闲时间是 10 秒
local ok, err = red:set_keepalive(10000, 100)
if not ok then
    ngx.say("failed to set keepalive: ", err)
    return
end