---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cun8c.
--- DateTime: 2019/7/1 9:13
---
---赋值运算符
print("=============赋值运算符=================")
a = 1
b = 2
c, d = 3, 4
e,f,g = 5, 6    --5,6,nil
h,j,k = 7,8,9,10    --7,8,9
print(a, b, c, d,e,f,g,h,j,k)
----算术运算符

print("=============算术运算符=================")
x = 10
y = 10
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x^y)
print(-(x-y))
print("=============关系运算符=================")
print(x==y)
print(x~=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)
print("=============关系运算符=================")
--and 类似于java的 &&
--or  类似于java的 ||
--not 类似于java的 !
print(true and false)       --false
print(true or false)        --true
print(false or true)        --true
print(false or false)       --false
print(not true)             --false
print("=============其他运算符=================")
--print(("hello world").len())
--print(len("hello world"))
print(#"hello world")       --求字符串长度
print("hello" .. "world")   --拼接字符串