---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cun8c.
--- DateTime: 2019/7/1 9:06
---
print(type(10))
print(type(3.5))
print(type("hello world"))
print(type(true))
print(type({name="zhangsan", age=23}))
print(type({{name="zhangsan", age=23}}))
print("====================================================================")
aa = 10
local bb = 20
function funcName(arg)
    cc = 30
    local dd = 40
    print(arg)
end
print(type(funcName))
funcName(12)            --调用函数以后，才能够获取cc的值， 因为调用以后才会初始化cc
print(aa)       --10
print(bb)       --20
print(cc)       --30
print(dd)       --nil