---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cun8c.
--- DateTime: 2019/7/1 9:49
---数组，长度不固定，下标从1开始
arr = {"aa", "bb", 123}

--1：使用数值for循环进行输出，下标从1开始
for i=1, #arr do
    print(arr[i])
end

--2：泛型for循环输出
for k, v in ipairs(arr) do   --key就是下标, v就是值
    print(k.."="..v)
end

for k, v in pairs(arr) do
    print(k.."="..v)
end