---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cun8c.
--- DateTime: 2019/7/1 9:54
---类型转换
---tostring
print(tostring(10))
print(tostring(10.2))
print(tostring(true))
print(tostring({name="zhangsan"}))

--tonumber
print(tonumber("10"))
print(tonumber("10", 16))
print(tonumber("aaqewqwwq"))
print(tonumber({x="zhang"}))